version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
     - checkout
     - run:
        name: Install npm dependencies
        comand:
          yarn install
     - run:
        name: Testing
        comand: 
          npm run test
workflows:
  build_test:
    jobs:
      - run_tests
     
